# Generated by Django 5.0.2 on 2024-02-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_img_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='product_imgs/%Y/%m/%d'),
        ),
    ]
