# Generated by Django 5.0.2 on 2024-03-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_category_product_category_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/product_imgs/%Y/%m/%d'),
        ),
    ]
